<?php

namespace EntityBundle\Repository;

/**
 * RfidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RfidRepository extends \Doctrine\ORM\EntityRepository
{
}
