<?php

namespace EntityBundle\Repository;

/**
 * Rfid_actRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rfid_actRepository extends \Doctrine\ORM\EntityRepository
{
}
